### ISSUE TITLE
Swift 3 Cocoapods Release? 

### ISSUE THREAD

**Issue by razvandub** [cezheng/Fuzi#34] opened 2016-09-15 12:42 UTC
Hi @cezheng, 

What's your time estimate for the Swift 3 cocoapods release? 

Thanks.

**Comment by cezheng** [comment] 2016-09-15 14:22
swift-3 branch is usable with CocoaPods at the moment.

```ruby
pod 'Fuzi', :git => 'https://github.com/cezheng/Fuzi.git', :branch => 'swift-3'
```

I'm not sure if it is a good time to merge Swift 3 into master and draft a new release. When I tried to upgrade another project, I found that many dependencies I use do not have Swift 3 support yet which means I have to delay the migration.

However I do think I need to do this as soon as possible, to help pushing people to Swift 3. By this weekend, after a bit of cleanup, I will draft a final release for Swift 2.3 & a release for Swift 3.

**Comment by cezheng** [comment] 2016-09-15 14:24
By that time, the current `swift-3` branch will be merged in to `master` and the branch itself will get deleted. The current `master` branch before the merge will be renamed to `swift2.3`.

**Comment by razvandub** [comment] 2016-09-15 14:26
Thanks @cezheng, tried swift-3 yet it's not building fine with the just released Xcode Version 8.0 (8A218a) -- must convert to current Swift syntax.

**Comment by cezheng** [comment] 2016-09-15 14:28
@razvandub Really? I remember successfully building it after upgrading to Xcode 8 the other day. And travis build is also passing. That `must convert` looks weird.

**Comment by razvandub** [comment] 2016-09-15 14:52
@cezheng, hmm... seems to be a cocoapods issue as the conversion does not affect the source files but Pods/Pods.xcodeproj/project.pbxproj, e.g., + SWIFT_VERSION = 3.0;. After "pods install" on a new project using cocoapods 1.0.1 the Pods' "Use Legacy Swift Language Version" build setting is set to "Unspecified" instead of  "Yes". Guess will have to use a post_install.

**Comment by cezheng** [comment] 2016-09-15 14:55
I retriggered travis build twice just now and both times yield different results( some of the platforms passes, some have issues code signing). I think I will take a look tomorrow.

**Comment by razvandub** [comment] 2016-09-15 15:00
Great, thanks. BTW, post_install did the trick.

**Comment by cezheng** [comment] 2016-09-15 15:02
Would you please share the post_install script you use? Someone else might see it and it can be quite helpful.

**Comment by razvandub** [comment] 2016-09-15 15:08
`post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            # Set "Use Legacy Swift Language Version" build setting to "NO", aka. "SWIFT_VERSION" to latest, "3.0".
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
`

**Comment by cezheng** [comment] 2016-09-15 15:10
Thanks. If this is a CocoaPods issue, someone might have opened an issue there.

**Comment by razvandub** [comment] 2016-09-15 15:17
Np. Some may argue though that it's not an issue as Xcode 8 allows devs to use/build either latest Swift 3.0 or legacy Swift 2.3. However, it would be nice if the Swift version could be specified in the podspec.

**Comment by cezheng** [comment] 2016-09-17 09:38
@razvandub 1.0.0 is shipped for Swift 3 now

**Comment by rhwood** [comment] 2016-09-17 12:42
Are you going to support the Swift Package Manager?

**Comment by cezheng** [comment] 2016-09-17 14:17
@rhwood When Swift went open source last year, I tried to add support for SPM but ended up with many problems with module map & many unimplemented Foundation methods on Linux.(#7), it just can't build.

At the moment, I still think Carthage or Cocoapods is better than SPM for iOS/macOS/tvOS/watchOS project though. I'm not sure if SPM handles pure Objective-C projects well.

Would you please tell me for what kind of project are you using SPM?

**Comment by rhwood** [comment] 2016-09-17 14:24
I am using an iOS app, but spent a significant time during the Swift 2.2 -> 3.0 upgrade swearing at CocoaPods. I'd also rather use what Apple ships than a third party manager.

**Comment by cezheng** [comment] 2016-09-18 03:41
@rhwood I see. I will take a look on SPM again.

**Closed** 2016-09-18 11:39 UTC

**Comment by cezheng** [comment] 2016-09-24 06:21
@rhwood 
Hi, I have tried supporting the SPM again, but once again no luck.

Let me explain a little bit about the reason.

## Why Carthage & CocoaPods work
* Fuzi uses libxml2, which is shipped with iOS, macOS, watchOS, tvOS. But no system module map is defined, so we have to define [one](https://github.com/cezheng/Fuzi/blob/master/libxml2/module.modulemap) ourselves.
* Defining this modulemap is not enough. Since the headers of libxml2 includes files in their directory, we have to set the header search path to let the compiler find those headers they include. Also, the headers' locations are different for different platforms, as well as different versions of SDKs. So we cannot write absolute path in the modulemap. We can take advantage of the $SDKROOT to determine the actual path of headers.
* Carthage just uses you xcodeproj's build settings, so if you xcodeproj builds, Carthage works. No extra efforts needed.
* CocoaPods does not use your xcodeproj, but it provides a way to specify you build setting in the [podspec](https://github.com/cezheng/Fuzi/blob/master/Fuzi.podspec#L24)

## Why SPM refuse to work?
* SPM provides no way to specify your build settings in your Package.swift. Only the user running `swift build` can pass some flags into it, which means the actual command you use with `swift build` is different for every platform as well as every SDK version.
* SPM is designed to refuse to run any commands. So we cannot use any kind of script to help us generate the build setting on different platforms.
* SPM added a feature to try to resolves this problem by introducing [pkgConfig](https://github.com/apple/swift-evolution/blob/master/proposals/0063-swiftpm-system-module-search-paths.md). But that is hopeless limited since it does not allow you attach a pkgConfig to your package, but just tell the SPM to look for *.pc files in the system path, which is only useful for some Linux libraries.

Max Howell is [extremely stubborn](https://bugs.swift.org/browse/SR-145) on insisting his own design principle, and just refuses to change any of those even if some of them has obviously make the package manager unusable on many cases.

**Comment by rhwood** [comment] 2016-09-24 14:23
Some questions and comments inline:

> Fuzi uses libxml2, which is shipped with iOS, macOS, watchOS, tvOS. But no system module map is defined, so we have to define one ourselves.

Is there a radar opened that I can indicate this affects me also?

> Defining this modulemap is not enough. Since the headers of libxml2 include files in their directory, we have to set the header search path to let the compiler find those headers they include. Also, the headers' locations are different for different platforms, as well as different versions of SDKs. So we cannot write absolute path in the modulemap. We can take advantage of the $SDKROOT to determine the actual path of headers.

Every Apple SDK I can download from within Xcode 8 has the libxml2 headers in $SDKROOT/usr/include/libxml2, so which platforms behave strangely?

On Linux, libxml2 has built it's *.pc file since 2005, so any Linux that includes the headers, but not the *.pc can be considered buggy in a way that you don't need to work around.

> SPM provides no way to specify your build settings in your Package.swift. Only the user running swift build can pass some flags into it, which means the actual command you use with swift build is different for every platform as well as every SDK version.
SPM is designed to refuse to run any commands. So we cannot use any kind of script to help us generate the build setting on different platforms.
> SPM added a feature to try to resolves this problem by introducing pkgConfig. But that is hopelessly limited since it does not allow you attach a pkgConfig to your package, but just tell the SPM to look for *.pc files in the system path, which is only useful for some Linux libraries.

Allowing this (or any) package to override the existing libxml2.pc files (which include architecture specific linker and build instructions) would be ~~brilliant~~brittle. I would hate to have the working *.pc get mangled and rendered unusable by a package relying on it when the developers of the using package did not allow for a specific architecture or build combination (the design of pkg-config files is that *.pc files are created at build time like *.so files are).

> Max Howell is extremely stubborn on insisting his own design principles, and just refuses to change any of those even if some of them has obviously make the package manager unusable on many cases.

Can you provide your work to date in a separate branch so I make take a crack at it?

> So can we make it work

> Yes, if we just copy all the sources from libxml2 and make a github repo for it, it is doable. But that also means you are not using the libxml2 that already exists in the OS's runtime, and the resulting binary of your app will get larger. This is just stupid.

This is no less stupid than including build instructions that potentially override the system provided build instructions, which is what you are currently insisting the Swift Package Manager support.

**Comment by cezheng** [comment] 2016-09-24 16:01
@rhwood 
I have already restructured the directory preparing for SPM support. You can just add a Package.swift yourself then begin your own hack.

> Every Apple SDK I can download from within Xcode 8 has the libxml2 headers in $SDKROOT/usr/include/libxml2, so which platforms behave strangely?

The problem is, there's no way for to get $SDKROOT's value if you use SPM, therefore you can not locate the headers' path. And there's no *.pc under $SDKROOT/usr/include/libxml2 which means there's literally no way for you to add a header search path.

> This is no less stupid than including build instructions that potentially override the system provided build instructions, which is what you are currently insisting the Swift Package Manager support.

I did not mean I want to override the system provided build instruction. I just want to provide my own instruction when the system provides no instruction. But SPM won't allow that.

**Comment by rhwood** [comment] 2016-09-24 16:23
> I have already restructured the directory preparing for SPM support. You can just add a Package.swift yourself then begin your own hack.

Thanks.

> And there's no *.pc under $SDKROOT/usr/include/libxml2 which means there's literally no way for you to add a header search path.

It should be under $SDKROOT/usr/lib<arch-if-applicable>/pkgconfig or in the System module map - libxml2 seems to be unique in missing in these locations (its a pity no-one filed a radar concerning this).

**Comment by muescha** [comment] 2016-12-07 23:31
just a note:

since Kanna also use libxml maybe you can look at the SPM section here:
https://github.com/tid-kijyun/Kanna#swift-package-manager

**Comment by cezheng** [comment] 2016-12-08 01:33
Well, Kanna is using the libxml2 headers in the Mac's system path rather than the libxml2 shipped with Xcode. Although since libxml2 is stable and won't change too much but I don't think using another version's libxml2 headers while linking with Xcode's libxml2 is correct.
